services:
    dbstudios_doze.serializer.entity_normalizer:
        class: DaybreakStudios\Doze\Serializer\EntityNormalizer

    dbstudios_doze.request.api_bag_converter:
        class: DaybreakStudios\DozeBundle\Request\ApiParameterBagConverter
        tags:
            - name: request.param_converter