parameters:
    dbstudios.cors_listener.enabled: true
    dbstudios.cors_listener.allowed_origins:
        - '*'
    dbstudios.cors_listener.allowed_headers:
        - '*'
    dbstudios.cors_listener.exposed_headers: []
    dbstudios.cors_listener.allowed_methods:
        - '*'
    dbstudios.cors_listener.allow_credentials: true

services:
    dbstudios_doze.cors_listener:
        class: DaybreakStudios\DozeBundle\Request\CORSListener
        public: false
        arguments:
            - '@logger'
            - '%dbstudios.cors_listener.enabled%'
            - '%dbstudios.cors_listener.allowed_origins%'
            - '%dbstudios.cors_listener.allowed_headers%'
            - '%dbstudios.cors_listener.allowed_methods%'
            - '%dbstudios.cors_listener.allow_credentials%'
            - '%dbstudios.cors_listener.exposed_headers%'
        tags:
            -
                name: monolog.logger
                channel: dbstudios_doze.cors_listener
            -
                name: kernel.event_listener
                event: kernel.response
                method: onKernelResponse
            -
                name: kernel.event_listener
                event: kernel.request
                method: onKernelRequest
                priority: 100

    dbstudios_doze.serializer.entity_normalizer:
        class: DaybreakStudios\Doze\Serializer\EntityNormalizer

    dbstudios_doze.request.api_bag_converter:
        class: DaybreakStudios\DozeBundle\Request\ApiParameterBagConverter
        tags:
            -
                name: request.param_converter